### ISSUE TITLE
problems with unloading nvidia module on fedora 18 with 3.9 kernel

### ISSUE THREAD

**Issue by gsgatlin** [Bumblebee-Project/Bumblebee#433]
Hello. Here are some logs:

messages log: http://pastebin.com/yvAPqJNL

xorg log: http://pastebin.com/haJ8LbAz

When a fedora 18 box with nvidia drivers 319.23 is booted. The nvidia card is off.

However, after one use, the card stays on until the next reboot.

The logs seems to indicate that the nvida module cannot be unloaded. I thought maybe this issue was related to #420 however, if I blacklist nvidia in grub2, it still doesn't fix the issue. (maybe blacklisting in grub only works for nouveau and not nvidia?)

I am getting random emails from people on the internet asking me to upgrade the nvidia drivers on fedora. (because of newer laptops I guess) But this seems unwise if the card will never shut off without a reboot. So I'm kind of not sure how I should proceed. Thanks for any ideas anyone has. I messed around with nvidia drivers all day yesterday and most problems seemed solvable (SELINUX issues, etc) but this one has me thinking is a show stopper for doing any upgrade. 

Please note this is only a problem in fedora 17/18/19. It is not showing up for me in CentOS kernel 2.6.32-358.6.2 with 319.23.. bbswitch turns off the card fine. But is for sure an issue with kernel 3.9.4-200 and 319.23.

Thanks so much for any ideas anyone might have.

**Comment by QkiZMR** [comment]
I have same issue. 

- Kernel 4.2.0-35-lowlatency,
- Ubuntu 15.10,
- Nvidia 840M and Intel,
- Nvidia 361.28 driver,
- Bumblebee 3.2.1-9,
- bbswitch-dkms 0.7-2ubuntu1.

After system boot nvidia gfx card is still active:
```
$ cat /proc/acpi/bbswitch 
0000:01:00.0 ON
```
When I make some console magic I can turn off nvidia card:
```
# rmmod nvidia_modeset
# rmmod nvidia_uvm (sometimes not necessary)
# rmmod nvidia
# tee /proc/acpi/bbswitch <<< OFF
```
and nvidia is turned off. On my power button I have LED that inform me what gfx card is used. Blue is for Intel, orange is for Nvidia. In normal behavior blue is lit when system finish booting. Now it's always orange because nvidia is still active. After disabling it by hand from command line LED is blue.

**Comment by ArchangeGabriel** [comment]
@QkiZMR What you’re seeing is #719.
