### ISSUE TITLE
syslog says: "bumblebeed[2846]: No integrated video card found, quitting"

### ISSUE THREAD

**Issue by akwala** [Bumblebee-Project/Bumblebee#524]
System: Ubuntu 13.10, 64-bit

Bumblebee seems not to find the Nvidia card, gdm starts in "low graphics" mode.

```
$ lspci -vmk | grep -A 8 -B 2 VGA
Device: 01:00.0
Class:  VGA compatible controller
Vendor: NVIDIA Corporation
Device: GF106M [GeForce GTX 460M]
SVendor:    CLEVO/KAPOK Computer
SDevice:    Device 5102
Rev:    a1
Driver: nvidia

Device: 01:00.1
```

... It _is_ an Optimus: http://www.geforce.com/hardware/notebook-gpus/geforce-gtx-460m

```
$ uname -a
Linux ubuntuSaucy 3.11.0-15-generic #23-Ubuntu SMP Mon Dec 9 18:17:04 UTC 2013 x86_64 x86_64 x86_64 GNU/Linux
```

```
$ dpkg --get-selections | grep nvidia
bumblebee-nvidia                install
nvidia-319                  install
nvidia-331                  install
nvidia-persistenced             install
nvidia-settings-331             install
```

```
$ grep -v '^$\|^\s*\#' /etc/bumblebee/bumblebee.conf | grep nvidia
[driver-nvidia]
KernelDriver=nvidia-331
LibraryPath=/usr/lib/nvidia-331:/usr/lib32/nvidia-331
XorgModulePath=/usr/lib/nvidia-331/xorg,/usr/lib/xorg/modules
XorgConfFile=/etc/bumblebee/xorg.conf.nvidia
```

**Comment by tick10** [comment]
alright so i seriously have this problem, when my machine had windows running on it i disabled intel hd graphics in the device manager because i was having issus getting my nvidia gpu to handle rendering tasks that could have been gpu excelerated but weren't. But since that moment when i disabled it neither windows nor the linux kernel can see my Intel Graphics. This is not like the first case, i have an i7 6700 hq cpu. it DEFINITELY has hd graphics built in. And the bios that comes with this pc is literally the shittiest bios ive seen on a pc since the freaking 90s it has like 6 settings total and 1 is whether or not i want to pc to beep when it starts. It's a custom laptop built by a company called xidax. I'm pretty sure its a custom motherboard and bios but i can't find ANY information out there about this board or bios. I've tried pulling the battery and power cord for several minutes to try and get the bios to reset with no luck. The laptops model number is p650re. if anyone has any suggestions id appreciate it. i can't get a response from the company that "built it"...
