### ISSUE TITLE
Xorg freeze after laptop suspend

### ISSUE THREAD

**Issue by qdel** [Bumblebee-Project/Bumblebee#625]
Hi,

I oftenly encounter an error with bumblebee, my installation is fully working and i can stop / start the gpu multiple times without problems.

But this, only at boot. After i put laptop to suspend (the gpu is at OFF at this moment), when i try to restart it, i don't have acpi errors, i have a 'infinite loop' Xorg taking one of my core!

Here are the logs:
Xorg
http://pastebin.com/eRNgreKN
dmesg
http://pastebin.com/RK72N2HW

A reboot fix the issue, but it break a bit the advantage of suspend :)

aser aspire V7-582pg (i5-4200u + gt 750m) 

Note: i sometimes have the "currently in D3" error. But if i put back then wakeup the laptop to suspend, it can go threw.

**Comment by Lekensteyn** [comment]
Does this only happen when you resume from suspend while optirun is active?

**Comment by qdel** [comment]
optirun is not active, I verify that everything is correctly shutdown. bbswitch says OFF and bumblebee xorg is shut down.

**Comment by ArchangeGabriel** [comment]
Sorry for the delay, could you please provide a full dmesg corresponding to boot + optirun + suspend + resume + (failed) optirun?

**Comment by qdel** [comment]
Hi,

So here are the logs.

1. boot
2. optirun glxgears
3. Working correctly
4. suspending laptop, waiting ~15 seconds before restart
5. restart laptop
6. optirun glxgears, fail here
  -> error: cannot enable discrete card.
      -> log dmesg.try.1
7. Putting back to suspend
8. restart laptop
9. optirun glxgears, another fail
  -> nothing... process doesn't end, nothing appear.
      -> log dmesg.try.2 / Xorg.8.log

**Comment by ArchangeGabriel** [comment]
I think you’ve forgotten the link.

**Comment by qdel** [comment]
Just corrected this...
For information, the bug reported by this ticket is at point 9... The point 6 is kind of random... sometime i don't have it for weeks....

**Comment by ArchangeGabriel** [comment]
OK. Does the Xorg.8.log really stop like this? I suppose so, since you say that the process does not end. What happen if you kill it (supplemental lines in both dmesg and xorg log especially)?

What I’ve found:

1. After each resume, you’ve got this message: `pci 0000:01:00.0: Max Payload Size 16384, but upstream 0000:00:1c.4 set to 128; if necessary, use "pci=pcie_bus_safe" and report a bug`.
2. In the first case, this cause bbswitch to be unable to bring the card back on with `pci 0000:01:00.0: Refused to change power state, currently in D3`. This does correspond to the last lines of your first post and the randomness you describe of it.
3. In the second case, it results in a lot of lost interruptions in the HPET (High Precision Event Timer), like this: `hpet1: lost 12 rtc interrupts`.

So, first of all I would try with the proposed kernel cmdline option. Could you do that and report results, in the same fashion as before?

Next, whether this works or not, I think this is going for bugreport against the kernel.

**Comment by qdel** [comment]
Yes, this instance of Xorg is a nice infinite loop, using one thread at 100%... it doesn't catch any signals... Totally unstopable.

The optirun glxgears command doesn't provide any output... only when I ^C it, but i think this output is usable or relevant:

optirun glxgears
^C[  459.915253] [WARN]Received Interrupt signal.
[  459.915295] [WARN]Could not read data! Error: Bad file descriptor
[  459.915302] [ERROR]Failed to retrieve LibraryPath setting.


I added the boot command line, no difference. i will try to see in my bios if HPET can be configured... But in a laptop bios, i don't believe so...

**Comment by ArchangeGabriel** [comment]
Hum, that does look bad, but also out of my knowledge.

Could you try with nouveau (still with Bumblebee) and eventually try PRIME? I can guide you in how to do that if you need.

If all of that fail, I would suggest you to try reporting and issue against the kernel, unless someone here has any idea on what to do next.

**Comment by qdel** [comment]
So, as expected, nothing in the bios about HPET (i know the option is available on my desktop motherboard)....

Adding the line in boot changed the error in dmesg as:
pci 0000:01:00.0: Max Payload Size set to 16384/ 256 (was 16384), Max Read Rq 16384

About my tries:
- with nouveau, same error after 1st sleep, after 2nd sleep, the whole computer is freeze...
- I tried to use prime a few weeks ago, but i never managed to be able to have the nvidia appear in xrandr listproviders...

**Comment by ArchangeGabriel** [comment]
For PRIME, you need nouveau to be loaded at X start and no xorg.conf file messing with the setup.

So, first, look at /etc/X11/xorg.conf.d and report the content here.

Then, two options:

1. Remove bumblebee and the corresponding modprobe blacklisting file, reboot, and see if nouveau appears in Xorg.0.log.
2. Stop bumblebee, make sure bbswitch is not loaded anymore and the card is on, restart X and see if nouveau appears in Xorg.0.log. Note that in this case you must reboot before being able to rmmod nouveau.

**Comment by qdel** [comment]
My xorg.conf is empty. I just have rules for my touchpad (synaptic)
I disabled bbswitch at boot and enabled nouveau.

Here is the output of dmesg:
http://pastebin.com/RqJFem1r (dmesg) (crash at second 59)

At boot, i can see both cards using xrandr --listproviders.
I make a little:
xrandr --setprovideroffloadsink nouveau Intel 

And try to use:
DRI_PRIME=1 glxinfo | grep "OpenGL renderer" 

At this, moment, Xorg crash and reboot. After reboot, nouveau card doesn't show on xrandr.

**Comment by ArchangeGabriel** [comment]
Hum indeed, with a GT750M you’re affected by https://bugs.freedesktop.org/show_bug.cgi?id=70354. BTW, that mean you can’t had nouveau running with Bumblebee but must have LLVMpipe rendering instead. Could you reproduce the same steps you did with NVIDIA above with nouveau this time and report the corresponding files (to get the dmesg, use journalctl -k -b -1 after reboot).

Next step will probably be reporting against kernel.

**Comment by qdel** [comment]
I don't understand which test you want me to reproduce. Using bumblebee with llvm pipe? Or with nouveau?

**Comment by ArchangeGabriel** [comment]
With nouveau. Would like dmesg and both Xorg.8.log (save the first one before retrying, or get the .old; obviously this is in case the second run does start X) for boot + optirun + suspend + resume + (failed) optirun.

**Comment by qdel** [comment]
Here are the logs (sorry, in holidays so i can't sit and my crash my laptop oftenly :) )

dmesg:
http://pastebin.com/mrx2zMuS

Xorg success:
http://pastebin.com/NCzuCBdG

Xorg fail:
http://pastebin.com/xquHCryG

**Comment by ArchangeGabriel** [comment]
OK, do you think you can report it upstream against kernel?

The things to report are:

1. After boot, everything is working, except you’re affected by https://bugs.freedesktop.org/show_bug.cgi?id=70354.
2. After first suspend, you see this line in your dmesg when resuming: `pci 0000:01:00.0: Max Payload Size 16384, but upstream 0000:00:1c.4 set to 128; if necessary, use "pci=pcie_bus_safe" and report a bug`.
3. At this stage, you can’t power on the NVIDIA card again, bbswitch trying to do so results in `pci 0000:01:00.0: Refused to change power state, currently in D3`.
4. Suspending and resuming again makes the same error appears, but this time the card can be powered on and off again. However, some messages `hpet1: lost 2 rtc interrupts` (with “2” varying, up to 37 currently) start to appears at each operation on the card, and trying to run something on it results in system freeze, with a lots of warnings in dmesg.

Also provides the three files from your last post.

If asked, say you can’t test with PRIME because of https://bugs.freedesktop.org/show_bug.cgi?id=70354.

And one last thing you might want to try before reporting, is once again the same steps but this time with `PMMethod=switcheroo` (instead of auto) under `[driver-nouveau]` in `/etc/bumblebee/bumblebee.conf`.

**Comment by qdel** [comment]
I will report to kernel. I tried to switch to switcheroo, but behavior is exactly same.

Thanks for your help!

**Comment by ArchangeGabriel** [comment]
If you have or when your will, could you link it here? Thanks.

**Comment by qdel** [comment]
https://bugzilla.kernel.org/show_bug.cgi?id=92011

But no answers for the moment :(

**Comment by qdel** [comment]
Hello,

I have some news about this bug!

I made some hard testing, and some really dirty (like really) dirty patch to bbswitch.
I need a few times to be sure of all the stuff i made who made it "fall working". but first investigations:

- disable laptop-tools
- Seems that being unplugged from AC give some help
- Complete disable of the pm callback inside bbswitch.c

What made me think of the problem is, just before suspend, i already have a line of error about 'card already in D3'... From this moment all other call would fail.

Still working on it. But this is good news!

**Comment by qdel** [comment]
Hi,

Was a bit tired yesterday, but it is still working:

- Laptop mode are disabled, they seems to put weird pm things (i use powertop + kde anyway to manage wifi and other stuff)
- AC plugged or not seems not to be a problem (it started to work while unplugged, thing which i don't do much when playing with graphic card...)
- The complete disable of the pm callback in bbswitch make things work


- At boot, graphic card is ON. It is directly usable. I shut it down with a kde autostart script. switch work without problem.
- At suspend, card can be ON or OFF, suspend work correctly
- Out of suspend, car is ON (it was OFF without the ugly hack), it is directly usable. switch work without problem. I put it off using a pm script.
- suspend can be chained without problems
- Shutdown can be ON or OFF without problems

I don't know what the exact problem is. But it is sure that the hook before suspend is not correctly executed.

My ugly hack is just to put a return; at the entry of the function, and manage ON / OFF via scripts.

I do believe it is a hardware problem still. Nouveau still have problems: HUB_INIT error like before. But now it doesn't freeze the whole system. Using DRI_PRIME with this card (when it appear) result in intel fallback. Not usable, but laptop don't freeze.

**Comment by jontis** [comment]
I think I have the same problem on an Acer v5-573g with nvidia GT750M

**Comment by jontis** [comment]
And yes it does freeze the whole system. Any way around this when it happens?
That's not ok.

**Comment by qdel** [comment]
I manage to make it work disabling the pm callback of bbswitch and using scripts. (seems where going too fast using pm...)

It was working on debian till my ssd nuke itself... Now i can't manage to make it work. Using kernel 4.2+, i have a "0000:01:00.0: Refused to change power state, currently in D3 " error all time i put laptop to sleep. This seems to happen when the kernel is waking up all devices.


Right now for me, the gt 750m is not usable on this laptop. (unless you just cold boot...)

**Comment by ArchangeGabriel** [comment]
Well, maybe there will be news soon since https://bugs.freedesktop.org/show_bug.cgi?id=70354 has been marked as RESOLVED FIXED. It should work with kernel 4.3 using `options nouveau config=War00C800_0=1` in some `.conf` file in `/etc/modprobe.d/` and rebuilding initramfs, and without this in 4.4.

This might not solve the whole issue here, but at least you should be able to try PRIME and see what it gives.

**Comment by ArchangeGabriel** [comment]
Hi people, what the status here? Things work like a charm for me since 4.4.

**Comment by qdel** [comment]
Quite a very late reply...

I do not use anymore bumblebee as it was really unstable until 4.10..

I instead use nouveau DRI_PRIME for 'mobile' use (this laptop have very weird reclock capabilities as it uses frequency from out of nowhere).

When I want to really use the nvidia card, I switch to nvidia Prime sync...

I indeed need to stop xorg, replace kernel driver restart xorg.

**Comment by qdel** [comment]
As stated, it is now stable (laptop still alive!).

DRI_PRIME reclocking is broken with nouveau. But loading Nvidia driver is ok.
Switch of driver is not a source of issues and seems to work fine.
