### ISSUE TITLE
Civilization: Beyond Earth crashes on virtualgl but not on primus

### ISSUE THREAD

**Issue by excieve** [Bumblebee-Project/Bumblebee#703]
When I try running the game through `optirun %command%` in steam the game segfaults with the following in the log:
```
steam.desktop[20833]: ERROR: ld.so: object 'libdlfaker.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
steam.desktop[20833]: ERROR: ld.so: object 'librrfaker.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
steam.desktop[20833]: X Error of failed request:  BadWindow (invalid Window parameter)
steam.desktop[20833]: Major opcode of failed request:  15 (X_QueryTree)
steam.desktop[20833]: Resource id in failed request:  0x200008
steam.desktop[20833]: Serial number of failed request:  98
steam.desktop[20833]: Current serial number in output stream:  98
kernel: CivBE[21258]: segfault at 18 ip 00000000096a4fb8 sp 00000000e9efef20 error 4 in CivBE[8048000+2d0c000]
```
It doesn't log this error and doesn't crash when run as `optirun -b primus %command%`. However, there are visual glitches instead that doesn't seem to happen on non-optimus setups.

**Comment by ArchangeGabriel** [comment]
Well, VirtualGL not working for some program is to be expected… And since we don’t do development of this program, plus the main developer don’t care a lot about our issues (which is quite normal), there is not a lot than can be done about this.

If you are having quantitative issues when running with either `primusrun` or `optirun -b primus`, please report them against primus. Closing this.
