### ISSUE TITLE
 /dev/dri/card0: failed to set DRM interface version 1.4: Permission denied

### ISSUE THREAD

**Issue by HaCk3Dq** [Bumblebee-Project/Bumblebee#733]
I am using git version of bumblebee with Arch Linux, kernel version `4.4.1-2`. When i try to launch an app it uses Intel card, i found a [hotfix](https://wiki.archlinux.org/index.php/bumblebee#.2Fdev.2Fdri.2Fcard0:_failed_to_set_DRM_interface_version_1.4:_Permission_denied) in arch-wiki, but it doesnt work.

```
$ systemctl status bumblebeed.service

● bumblebeed.service - Bumblebee C Daemon
   Loaded: loaded (/usr/lib/systemd/system/bumblebeed.service; enabled; vendor preset: disabled)
   Active: active (running) since Пт 2016-02-12 17:48:15 MSK; 31min ago
 Main PID: 453 (bumblebeed)
    Tasks: 1 (limit: 512)
   CGroup: /system.slice/bumblebeed.service
           └─453 /usr/bin/bumblebeed --use-syslog

systemd[1]: Started Bumblebee C Daemon.
bumblebeed[453]: /usr/bin/bumblebeed 3.2.1-18-g3c6f9c9 started
bumblebeed[453]: [XORG] (WW) `fonts.dir' not found (or not valid) in "/usr/share/fonts/100dpi/".
bumblebeed[453]: [XORG] (WW) `fonts.dir' not found (or not valid) in "/usr/share/fonts/75dpi/".
bumblebeed[453]: [XORG] (EE) /dev/dri/card0: failed to set DRM interface version 1.4: Permission denied
bumblebeed[453]: [XORG] (WW) NVIDIA(0): Unable to get display device for DPI computation.
bumblebeed[453]: [XORG] (EE) /dev/dri/card0: failed to set DRM interface version 1.4: Permission denied
bumblebeed[453]: rmmod: ERROR: Module nvidia_uvm is not currently loaded
bumblebeed[453]: modprobe: FATAL: Error running remove command for nvidia
```

**Comment by xed** [comment]
Hi!
same problem.
kernel version: 4.4.1-2-ARCH
bumblebee-git-3.2.1.r18.3c6f9c9-1
nvidia driver version: 361.28-1


`systemctl status -l bumblebeed
● bumblebeed.service - Bumblebee C Daemon
   Loaded: loaded (/usr/lib/systemd/system/bumblebeed.service; enabled; vendor preset: disabled)
   Active: active (running) since Fri 2016-02-19 11:56:07 MSK; 1h 2min ago
 Main PID: 942 (bumblebeed)
    Tasks: 2 (limit: 512)
   CGroup: /system.slice/bumblebeed.service
           ├─  942 /usr/bin/bumblebeed --use-syslog
           └─12157 /usr/lib/xorg-server/Xorg :8 -config /etc/bumblebee/xorg.conf.nvidia -configdir /etc/bumblebee/xorg.conf.d -sharevts -nolisten tcp -noreset -verbose 3 -isolateDevice PCI:03

Feb 19 11:56:07 xed-head systemd[1]: Started Bumblebee C Daemon.
Feb 19 11:56:07 xed-head bumblebeed[942]: /usr/bin/bumblebeed 3.2.1-18-g3c6f9c9 started
Feb 19 12:57:45 xed-head bumblebeed[942]: [XORG] (WW) `fonts.dir' not found (or not valid) in "/usr/share/fonts/100dpi/".
Feb 19 12:57:45 xed-head bumblebeed[942]: [XORG] (WW) `fonts.dir' not found (or not valid) in "/usr/share/fonts/75dpi/".
Feb 19 12:57:45 xed-head bumblebeed[942]: [XORG] (EE) /dev/dri/card0: failed to set DRM interface version 1.4: Permission denied
Feb 19 12:57:45 xed-head bumblebeed[942]: [XORG] (WW) Warning, couldn't open module mouse
Feb 19 12:57:45 xed-head bumblebeed[942]: [XORG] (WW) NVIDIA(0): Unable to get display device for DPI computation.
Feb 19 12:57:45 xed-head bumblebeed[942]: [XORG] (WW) Warning, couldn't open module mouse
Feb 19 12:57:45 xed-head bumblebeed[942]: [XORG] (EE) /dev/dri/card0: failed to set DRM interface version 1.4: Permission denied
`

**Comment by ziXet** [comment]
Same here.
kernel: 4.4.1-2-ARCH
bumblebee: 3.2.1

**Comment by bedil** [comment]
same here.
4.4.2 tumbleweed
Bumblebee throws this error:
(EE) /dev/dri/card0: failed to set DRM interface version 1.4: Permission denied 

I have been unable to make bumblebee work. It throws many kinds of errors. 
(EE) Screen(s) found, but none have a usable configuration.

dmesg:
[   42.643739] bbswitch: enabling discrete graphics
[   42.863658] [drm] Initialized nvidia-drm 0.0.0 20150116 for 0000:01:00.0 on minor 0
[   42.863663] NVRM: loading NVIDIA UNIX x86_64 Kernel Module  352.63  Sat Nov  7 21:25:42 PST 2015
[   42.865365] nvidia_uvm: Loaded the UVM driver, major device number 246
[   43.072947] vgaarb: this pci device is not a vga device
[   43.089239] ACPI Warning: \_SB_.PCI0.PEG0.PEGP._DSM: Argument #4 type mismatch - Found [Buffer], ACPI requires [Package] (20150930/nsarguments-95)
[   51.239101] NVRM: failed to copy vbios to system memory.
[   51.247133] NVRM: RmInitAdapter failed! (0x30:0xffff:851)
[   51.248659] NVRM: rm_init_adapter failed for device bearing minor number 0
[   51.249098] NVRM: nvidia_frontend_open: minor 0, module->open() failed, error -5
[   64.764406] SFW2-INext-DROP-DEFLT IN=wlp3s0 OUT= MAC=54:27:1e:97:a8:7b:0c:d2:b5:51:b3:18:08:00 SRC=10.10.7.81 DS

Card: Geforce GTX 870M
01:00.0 3D controller: NVIDIA Corporation GK104M [GeForce GTX 870M] (rev a1)

I have looked at hundreds of pages, including all the old issues on this page, and have still not been able to solve this issue. Sometimes it works randomly, but then crashes the next time, and then one of the many errors keep reappearing.

**Comment by Luke-Nukem** [comment]
Hi all. I came across this error while packaging BB for another distro a little while ago. I haven't solved it, but I have some theories on why it has happened.
* PAM modules have changed, and results in a change of permissions, or
* systemd authentication/permissions have changed.

I don't have time to follow up on my thoughts, unfortunately as University has started again.

**Comment by danfloyd111** [comment]
Same here with openSUSE Leap 42.1 on Asus N550JK with IntelHD + Nvidia Geforce GTX 850M and Bumblebee 3.2.1. And that's not all... the strangest thing is that sometimes it works and I can't figure out why, if I do exactly the same thing, 1 sec after it not works anymore:
`dan@suse-linux:[bumblebee]:$ optirun glxspheres           
Polygons in scene: 62464 (61 spheres * 1024 polys/spheres)
Visual ID of window: 0x20
Context is Direct
OpenGL Renderer: Gallium 0.4 on NV117
151.090529 frames/sec - 168.617030 Mpixels/sec
152.288068 frames/sec - 169.953484 Mpixels/sec
150.915714 frames/sec - 168.421937 Mpixels/sec
151.517466 frames/sec - 169.093492 Mpixels/sec
150.631511 frames/sec - 168.104766 Mpixels/sec
150.596822 frames/sec - 168.066053 Mpixels/sec
150.804838 frames/sec - 168.298199 Mpixels/sec
151.105529 frames/sec - 168.633771 Mpixels/sec
150.929111 frames/sec - 168.436888 Mpixels/sec
151.043571 frames/sec - 168.564625 Mpixels/sec
dan@suse-linux:[bumblebee]:$ optirun glxspheres
[  579.323229] [ERROR]Cannot access secondary GPU - error: [XORG] (EE) /dev/dri/card0: failed to set DRM interface version 1.4: Permission denied

[  579.323260] [ERROR]Aborting because fallback start is disabled.
`

n.b. these commands were executed in sequence as shown.

**Comment by anfractuosity** [comment]
Same issue here, under Arch, 4.4.1-2-ARCH 

```
Mar 03 13:12:18 i7 bumblebeed[450]: [ 1103.941841] [WARN][XORG] (WW) `fonts.dir' not found (or not valid) in "/usr/share/fonts/100dpi/".
Mar 03 13:12:18 i7 bumblebeed[450]: [ 1103.941852] [WARN][XORG] (WW) `fonts.dir' not found (or not valid) in "/usr/share/fonts/75dpi/".
Mar 03 13:12:18 i7 bumblebeed[450]: [ 1103.941869] [ERROR][XORG] (EE) /dev/dri/card1: failed to set DRM interface version 1.4: Permission denied
Mar 03 13:12:18 i7 bumblebeed[450]: [ 1103.941871] [ERROR][XORG] (EE) /dev/dri/card0: failed to set DRM interface version 1.4: Permission denied
Mar 03 13:12:18 i7 bumblebeed[450]: [ 1103.941879] [WARN][XORG] (WW) NVIDIA(0): Unable to get display device for DPI computation.
Mar 03 13:12:18 i7 bumblebeed[450]: [ 1103.941887] [ERROR][XORG] (EE) /dev/dri/card1: failed to set DRM interface version 1.4: Permission denied
Mar 03 13:12:18 i7 bumblebeed[450]: [ 1103.941888] [ERROR][XORG] (EE) /dev/dri/card0: failed to set DRM interface version 1.4: Permission denied
Mar 03 13:12:18 i7 kernel: ACPI Warning: \_SB_.PCI0.PEG0.PEGP._DSM: Argument #4 type mismatch - Found [Buffer], ACPI requires [Package] (20150930/nsarguments-95)
Mar 03 13:12:19 i7 bumblebeed[450]: rmmod: ERROR: Module nvidia is in use by: nvidia_modeset
Mar 03 13:12:22 i7 bumblebeed[450]: [ 1107.045421] [ERROR]Unloading nvidia driver timed out.
Mar 03 13:12:25 i7 acpid[457]: client 1947[0:56] has disconnected
Mar 03 13:12:25 i7 acpid[457]: client 1947[0:56] has disconnected
```

**Comment by ArchangeGabriel** [comment]
All your people here seems to have different issues, and the DRM things isn’t one normally (harmless message). So, I’m closing this and ask each one of you to open a new issue with a more detailed description of your issue, what works and what does not, full logs (reboot before tries, use gist to paste logs).
