### ISSUE TITLE
Expand over multi-monitors HDMI wired to nvidia

### ISSUE THREAD

**Issue by shrimpwagon** [Bumblebee-Project/Bumblebee#763]
"When the port is wired into the nvidia chip, you cannot currently expand the screen over monitors"

I'm sure you get asked this all the time but I simply got to know if there is a time-frame on getting this to work. I've been looking everywhere and this is my only hope it looks like.

Thanks for all you do!

**Comment by ArchangeGabriel** [comment]
Hi. I’m not sure what is the state of multi-monitor today (that’s tracked at #77, I’ve just pinged there to know about that). From what I remember, the state under Linux has not progressed. You might also read #577 which has some interesting information on the topic, but the short version is core components of Linux aren’t supporting this OOTB (except maybe through PRIME, not sure about that), while Windows seems to…

Anyway, it’s not on Bumblebee side that anything could be done, so I’m closing this and keeping #77 for tracking progress on that subject.

Also, notes that no dev here has a laptop with an output wired to the nvidia chip, so we can’t test anything…

**Comment by shrimpwagon** [comment]
Thank you for the response.

I can disable Nvidia Optimus in the BIOS. Does this mean that the HDMI should then work through the Intel chip? When I disable Optimus in the BIOS the HDMI still doesn't work and the desktop display settings does not recognize it as an external montior. I'm not 100% sure if the HDMI is wired directly into the Nvidia but everything seems to be pointing to that.

I really care less about graphics performance. I just wont to use dual-monitors. I'm ok with the main laptop display being turned off.

Any pointers would be very helpful. Thank you again!

**Comment by ArchangeGabriel** [comment]
If it’s wired to the Nvidia chip, no, turning Optimus off would also totally disable that port.

I’m not sure what could be done in your case. You’re writing about dual-monitors with laptop display off: so, you’re connecting two external screens? One on HDMI, on the other on DP/VGA I suppose?

Anyway, I think that PRIME might help, found this for example: https://dchambers.github.io/articles/driving-multiple-monitors-on-an-optimus-laptop/. Like I said, I’ve never dived deep into the subject, because can’t test (and until two months ago, can’t use nouveau either).

You have multiple way with that, you could also try reverse PRIME that give you the opportunity to run everything on the Nvidia card.
