### ISSUE TITLE
Fedora 25 - Kernel: 4.10.3-200.fc25.x86_64 - modinfo: ERROR: Module nvidia not found.

### ISSUE THREAD

**Issue by Simon-Davies** [Bumblebee-Project/Bumblebee#853]
bumblebee-nvidia --check
--force compile selected via /etc/sysconfig/nvidia/compile-nvidia-driver
Warning! This NVIDIA driver has not compiled successfully before on kernel 4.10.3-200.fc25.x86_64!
Warning! This NVIDIA driver userland
 /usr/lib64/nvidia-bumblebee/libGL.so.1 library is missing!

Warning! nvidia.ko was not created in in the kernel tree!
modinfo output for NVIDIA:

modinfo: ERROR: Module nvidia not found.

Check bbswitch kernel module...

bbswitch is loaded into the current kernel ok.

All NVIDIA checks completed, but there were 1 or more failures...
Try running this script with the --debug option to find clues about what has
gone wrong with the NVIDIA driver compile process.

**Comment by Simon-Davies** [comment]
bumblebee-nvidia --debug
--force compile selected via /etc/sysconfig/nvidia/compile-nvidia-driver
--debug mode selected.
Building NVIDIA video drivers: Creating directory NVIDIA-Linux-x86_64-375.39
Verifying archive integrity... OK
Uncompressing NVIDIA Accelerated Graphics Driver for Linux-x86_64 375.39.........................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................

ERROR: An error occurred while performing the step: "Building kernel modules". See /var/log/nvidia-installer.log for details.


ERROR: The nvidia kernel module was not created.


ERROR: Installation has failed.  Please see the file '/var/log/nvidia-installer.log' for details.  You may find suggestions on fixing installation
       problems in the README available on the Linux driver download page at www.nvidia.com.

				   [FAILED]

**Comment by Simon-Davies** [comment]
[nvidia-installer.log.txt](https://github.com/Bumblebee-Project/Bumblebee/files/852857/nvidia-installer.log.txt)

**Comment by Simon-Davies** [comment]
From reading the nvidia-installer.log this seems to be a problem with the Nvidia Driver compiling on the 4.10 kernel

**Comment by gsgatlin** [comment]
@Simon-Davies 

You can run:

dnf clean expire-cache

dnf update bumblebee-nvidia

This should update to bumblebee-nvidia-375.39-3.fc25 which adds a patch to build on kernel 4.10.

Thanks for heads up about issue.

**Comment by kmare** [comment]
I think the latest patches won't apply on a 4.9.x kernel. At least I haven't updated yet to 4.10, have the new bumblebee-nvidia package and running bumblebee-nvidia --force will give me:

patching file kernel/common/inc/nv-mm.h
patching file kernel/nvidia-drm/nvidia-drm-fence.c
patching file kernel/nvidia-drm/nvidia-drm-gem.h
patching file kernel/nvidia-drm/nvidia-drm-priv.h
patching file kernel/nvidia/nv-pat.c
				   [FAILED]

**Comment by gsgatlin** [comment]
It worked on my machine with 4.9.14-200.fc25.x86_64. I did not update to 4.10 on my machine either. But I tested it on both kernels with a test laptop. Sorry. I am not sure why it is not working. I guess you will want to downgrade until 4.10 is out of testing?

**Comment by kmare** [comment]
I'm sorry, never mind. It was a different error: 
ERROR: An NVIDIA kernel module 'nvidia-drm' appears to already be loaded in your kernel.  This may be because it is in use (for example, by an X server, a CUDA program, or the NVIDIA Persistence Daemon), but this may also happen if your kernel was configured without support for module unloading.

so yeah, guess it's because the module is already loaded. Thank you for updating to 4.10! I'll upgrade and report back as soon as I can,

**Comment by gsgatlin** [comment]
Seems like when I've seen similar a reboot helped in the past.

**Comment by Simon-Davies** [comment]
The Nvidia driver is now compiling on Kernel 4.10 and Bumblebee is working :) Thanks guys. You can close this issue as it's been resolved.

**Comment by PrzemekSkw** [comment]
Hi, I use Fedora 25 with x.org and todays update broke my bumblebee. Driver updated is bumblebee-nvidia-375.39-3.fc25.x86_64. Terminal output is:
`primusrun glxspheres                                                                                                                                           
primus: fatal: Bumblebee daemon reported: error: Could not load GPU driver `
can somebody help?

**Comment by gsgatlin** [comment]
@PrzemekSkw can you downgrade the driver and reboot? Does that help?

dnf downgrade bumblebee-nvidia
reboot

**Comment by gsgatlin** [comment]
@PrzemekSkw if that doesn't work then can you post logs to pastebin or similar sites?

journalctl output and also /var/log/Xorg.8.log

Also, what is the output from

bumblebee-nvidia --check

**Comment by PrzemekSkw** [comment]
@gsgatlin Thank You, downgrade helps. But what if further updates will crash bumblebee ?

**Comment by gsgatlin** [comment]
@PrzemekSkw I would hold off on updating bumblebee-nvidia until either kernel 4.10 comes out to fedora updates or until nvidia releases a newer "long lived branch" version. Sorry this update caused issues on your machine. Its weird that its working on my box. These kernel updates can be tricky timing wise.

**Comment by Simon-Davies** [comment]
I'm using Fedora 25 Kernel 4.10 and have the testing repository enabled. Bumblebee is working perfectly after:

sudo dnf update bumblebee-nvidia.

Thank you

**Comment by PrzemekSkw** [comment]
@gsgatlin I find problem. I have lightdm insteda gdm. Now I switch to GDM and everything works :)

**Comment by PrzemekSkw** [comment]
Everything works well but I have error when I close my system:
`Failed to start Compiling NVidia Driver`
How to fix it?

**Comment by gsgatlin** [comment]
@PrzemekSkw 

What happens if you run

systemctl start bumblebee-nvidia.service

Does that give you an error?

**Comment by PrzemekSkw** [comment]
@gsgatlin I had strange problem because when I turn on my laptop bumblebee don't work, I must reboot if I want to bumblebee work. Now I upgrade kernel to 4.10.4 from fedora testing repo, downgrade bumblebee-nvidia and upgrade it to newest version and for now everything works :)

**Comment by PrzemekSkw** [comment]
@gsgatlin Sory, after some time problem returns :/

**Comment by gsgatlin** [comment]
@PrzemekSkw I am sorry you are having trouble. The nvidia driver gets installed by a shell script. The shell script puts a flag (file) on the system to tell it if it succeed or not. Then if it did succeed it does nothing until either the package gets upgraded or the kernel updates. And the script gets run at every boot by systemd init system.

Here is the output of some commands on my working system:

bumblebee-nvidia --check
bumblebee-nvidia
systemctl start bumblebee-nvidia.service

https://paste.fedoraproject.org/paste/jwGivVZOV-gWGVgtpj7Y~F5M1UNdIGYhyRLivL9gydE=

The first command dumps some output showing all checks passed and everything should be working.

The second command shows no output because it already succeeded before during a reboot some time a few days ago.

The third command just gives no output because everything is working correctly.

I pasted the output into https://paste.fedoraproject.org/

Here is the link:

https://paste.fedoraproject.org/paste/jwGivVZOV-gWGVgtpj7Y~F5M1UNdIGYhyRLivL9gydE=

Can you paste the output from those same commands on your system into  https://paste.fedoraproject.org/ and post the link back here? Then perhaps we can figure out what has gone wrong.

Thanks.

**Comment by PrzemekSkw** [comment]
@gsgatlin Now I discover it's not from the closed laptop lid. The problem is random. Everything was OK and after some time bumblebee stop working: `primusrun glxspheres
primus: fatal: Bumblebee daemon reported: error: Could not load GPU driver`

Output look like this:

1. 
[https://paste.fedoraproject.org/paste/-EEz~oRhyZC5UTmzI7Zk2F5M1UNdIGYhyRLivL9gydE=](url)

2.
[https://paste.fedoraproject.org/paste/Iz0I5eivVKtZD54pBHdYhl5M1UNdIGYhyRLivL9gydE=](url)

3.
[https://paste.fedoraproject.org/paste/ufeJj5pMHpIUpeoErPVG5F5M1UNdIGYhyRLivL9gydE=](url)

And some extra outputs:
[https://paste.fedoraproject.org/paste/7dLaafm9UMsO7QmIbaeOUV5M1UNdIGYhyRLivL9gydE=](url)
[https://paste.fedoraproject.org/paste/qoxZyFynLUhiO-FQuLWJCF5M1UNdIGYhyRLivL9gydE=](url)

**Comment by gsgatlin** [comment]
@PrzemekSkw Ok. So it doesn't like that patch. What happens when you type:

(as root)

mv /etc/sysconfig/nvidia/kernel_4.10.patch /root/kernel_4.10.patch

Then type:

bumblebee-nvidia

Can you paste the output from that? Thanks.

**Comment by PrzemekSkw** [comment]
Also failed:
`[root@przemek przemek]# mv /etc/sysconfig/nvidia/kernel_4.10.patch /root/kernel_4.10.patch
[root@przemek przemek]# bumblebee-nvidia
--force compile selected via /etc/sysconfig/nvidia/compile-nvidia-driver
Building NVIDIA video drivers: Creating directory NVIDIA-Linux-x86_64-375.39
Verifying archive integrity... OK
Uncompressing NVIDIA Accelerated Graphics Driver for Linux-x86_64 375.39.........................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................
				   [FAILED]
[root@przemek przemek]# 
`

**Comment by gsgatlin** [comment]
Ah. Ok. Try

bumblebee-nvidia --debug

what is the output from that command?

Also, after you run that command can you paste the output from

/var/log/nvidia-installer.log

into

https://paste.fedoraproject.org/

and post the link to that here? Thanks.

**Comment by PrzemekSkw** [comment]
OK,
first output:
[https://paste.fedoraproject.org/paste/cmY94sAglIh5Ap6ifB5dU15M1UNdIGYhyRLivL9gydE=](url)
and the second:
[https://paste.fedoraproject.org/paste/NYvkDSQGV4-We~vLRIeqk15M1UNdIGYhyRLivL9gydE=](url)

**Comment by gsgatlin** [comment]
Ok. so what is going on here is that you have a 4.10 kernel. But for some reason the patch does not work on your computer. I honestly do not know why it doesn't work on your system. Its very strange.

I will give it some more thought. maybe there is a way we can see more of why the patch failed on your system. Perhaps it can be redone. I will look at it tonight.

**Comment by PrzemekSkw** [comment]
OK, thanks for helping me. I will wait for news.

**Comment by gsgatlin** [comment]
Hey, I thought about some more. I wonder if the patch is working but it fails for some other reason. Try doing this:
(Put patch back)

mv /root/kernel_4.10.patch /etc/sysconfig/nvidia/kernel_4.10.patch

reboot

wait like at least 5 minutes for bumblebee-nvidia to try and then fail.

Then run as root:

bumblebee-nvidia --debug

and paste the output from that.

Than after you do that post the new logfile it made:

/var/log/nvidia-installer.log

into

https://paste.fedoraproject.org/

and post the link to that here? Thanks.

**Comment by PrzemekSkw** [comment]
I do as You told. Now after reboot bumblebee don't work. 
That is 'bumblebee-nvidia --debug' output:
[https://paste.fedoraproject.org/paste/MhzjdvPt--J-pDBjla~Lfl5M1UNdIGYhyRLivL9gydE=](url)
and log file
[/var/log/nvidia-installer.log](url)

**Comment by gsgatlin** [comment]
@PrzemekSkw Sorry we were really busy today at work. I looked the output and the good news is that the patch is working. But something else failed. 

Kernel module load error: No such device

can you paste output from

lspci | grep VGA

Do you know what kind of video chip your nvidia is? Like I have a 740M.

Thanks.

**Comment by gsgatlin** [comment]
wondering if this is the pcie_port_pm=off bug you hit.

**Comment by PrzemekSkw** [comment]
Hi, thats the output:
`00:02.0 VGA compatible controller: Intel Corporation 3rd Gen Core processor Graphics Controller (rev 09)
01:00.0 VGA compatible controller: NVIDIA Corporation GF108M [GeForce GT 630M] (rev a1)
`

> wondering if this is the pcie_port_pm=off bug you hit.
Don't understand what do You mean. :)

**Comment by gsgatlin** [comment]
I was thinking you might be seeing this?

https://fedoraproject.org/wiki/Bumblebee#Broken_power_management_with_kernel_4.8

**Comment by gsgatlin** [comment]
what is the output from:

cat /proc/cmdline

?

Thanks.

**Comment by PrzemekSkw** [comment]
Hi, I don't have that laptop for the weekend so I can't check the output. My laptop is older than 2015. 
The good thing is that yesterday I reinstall bumblebee and today everything was OK :) except that long time took bumblebee.service on boot.

**Comment by gsgatlin** [comment]
@PrzemekSkw Ok. Glad you got it to work then.

**Comment by PrzemekSkw** [comment]
@gsgatlin Hi today when I'm back in home is again broken :\ 
Output:
`BOOT_IMAGE=/boot/vmlinuz-4.10.4-200.fc25.x86_64 root=UUID=0f8c235b-6cf7-4c0a-b4f4-b4d2293acbdf ro nouveau.modeset=0 rd.driver.blacklist=nouveau rhgb quiet LANG=pl_PL.UTF-8`

**Comment by gsgatlin** [comment]
Does turning off SELinux 

getenforce 0

then running the script

/usr/sbin/bumblebee-nvidia --debug

produce a green [OK] or a red [FAILURE] ?

If its still red, I am running out of ideas to try. The basic problem was that you cannot load the kernel module because it says "Kernel module load error: No such device" and I am unsure how you can get past that. Perhaps some others here will have some ideas.

**Comment by gsgatlin** [comment]
Oh, Can you also post the /var/log/messages or output from journalctl to  https://paste.fedoraproject.org/ and paste link back to that here as you run /usr/sbin/bumblebee-nvidia --debug ? Thanks.

**Comment by gsgatlin** [comment]
Actually, I have some other ideas we can try if these suggestions don't help concerning selinux. But lets see what happens with that first.

**Comment by PrzemekSkw** [comment]
Hi, the first output is also failed :(
https://paste.fedoraproject.org/paste/yGz8l4itf~PQYDjokieOXV5M1UNdIGYhyRLivL9gydE=

and the journalctl -b output:
https://paste.fedoraproject.org/paste/4MmLxMb9v39UbmKky3z5hF5M1UNdIGYhyRLivL9gydE=

**Comment by gsgatlin** [comment]
@PrzemekSkw Do you know what kind of graphics chip your notebook has?

I see this in your log:

mar 27 08:20:52 przemek sudo[9081]: pam_unix(sudo:session): session opened for user root by (uid=0)
mar 27 08:21:22 przemek kernel: nvidia 0000:01:00.0: vgaarb: changed VGA decodes: olddecodes=none,decodes=none:owns=none
mar 27 08:21:22 przemek kernel: NVRM: The NVIDIA GPU 0000:01:00.0 (PCI ID: 10de:0de9)
                                NVRM: installed in this system is not supported by the 375.39
                                NVRM: NVIDIA Linux driver release.  Please see 'Appendix
                                NVRM: A - Supported NVIDIA GPU Products' in this release's
                                NVRM: README, available on the Linux driver download page
                                NVRM: at www.nvidia.com.
mar 27 08:21:22 przemek kernel: nvidia: probe of 0000:01:00.0 failed with error -1

**Comment by PrzemekSkw** [comment]
I have:
 NVIDIA Corporation GF108M [GeForce GT 630M]

**Comment by PrzemekSkw** [comment]
If it's not supported with new driver I will downgrade :/

**Comment by gsgatlin** [comment]
Yeah. Let me check out the readme and I'll let you know what we can try next.

**Comment by gsgatlin** [comment]
Its very strange. Your card should be supported with that version. Perhaps its a bug in the driver.

I have a test machine with slightly older card and it works fine:

[gsgatlin@y470c ~]$ lspci | grep VGA
00:02.0 VGA compatible controller: Intel Corporation 2nd Generation Core Processor Family Integrated Graphics Controller (rev 09)
01:00.0 VGA compatible controller: NVIDIA Corporation GF108M [GeForce GT 550M] (rev ff)

I don't see that message about not supported. I do see it on console output but I always just ignore that one since it always lies.

You can try:

[root@y470c ~]# mv /etc/sysconfig/nvidia/NVIDIA-Linux-x86_64-375.39.run /root

Then download ‘NVIDIA-Linux-x86_64-378.13.run’

[root@y470c ~]# wget http://us.download.nvidia.com/XFree86/Linux-x86_64/378.13/NVIDIA-Linux-x86_64-378.13.run

mv NVIDIA-Linux-x86_64-378.13.run /etc/sysconfig/nvidia/

(It still needs the patch since nvidia doesn't even support 4.10 kernel yet...)

Then run 

[root@y470c ~]# bumblebee-nvidia --debug --force

Does that version work any better?

Do you see a green OK after that?

**Comment by PrzemekSkw** [comment]
@gsgatlin Hi, two days ago was kernel upgrade and since then bumblebee works fine :) I don;t know for how long but now is OK. 
Not thanking for help yet  :D
Bye

**Comment by edugsdf** [comment]
Unfortunately for me to continue with error. Can someone help me?

bumblebee-nvidia --check:
https://paste.fedoraproject.org/paste/qF2OCMK66g7eSWq7pAfZ115M1UNdIGYhyRLivL9gydE=

bumblebee-nvidia --debug:
  

> --debug mode selected.

systemctl status bumblebee-nvidia.service:
https://paste.fedoraproject.org/paste/moFWKdAD~toWEBY8QNqXdV5M1UNdIGYhyRLivL9gydE=


/var/log/nvidia-installer.log:
https://paste.fedoraproject.org/paste/Y7H8-WUVX0-fC44heGkL0F5M1UNdIGYhyRLivL9gydE=

uname -a:

> Linux system 4.10.8-200.fc25.x86_64 #1 SMP Fri Mar 31 13:20:22 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

**Comment by gsgatlin** [comment]
@edugsdf what happend if you type

modprobe bbswitch


?
