### ISSUE TITLE
[Help] Update bumblebee because of a new kernel.

### ISSUE THREAD

**Issue by EgamoPi** [Bumblebee-Project/Bumblebee#864]
Good morning all,
already second post on this project aha^^ Well last time I asked help on how to install bumblebee on my machine, here's the link :  https://github.com/Bumblebee-Project/Bumblebee/issues/862 for my laptop I had to use the backports repository etc.. My kernel version is now : 
```
egamo@omega:~$ cat /proc/version 
Linux version 3.16.0-4-amd64 (debian-kernel@lists.debian.org) (gcc version 4.8.4 (Debian 4.8.4-1) ) #1 SMP Debian 3.16.39-1+deb8u2 (2017-03-07)

```
But when I use thebackports to install my wifi driver : apt-get -t jessie-backports install linux-image-amd64 firmware-atheros something magic happens, my wifi work perfectly, I can use my display (before my laptop wasn't recognizing it even tho bumblebee workED) and this is really cool..But bumblebee is no more working, the switch between cards doesn't work, and I was blocked on the nvidia.
Now I did a fresh install, installed bumblebee but not yet the wifi card and new kernel : Do you have any idea on how to deal with that ? Update bumblebee after the installation of the new kernel etc..? 
And stupid question : How come on installing only the wifi card my kernel updated, my sceen was recognize etc etc..?
Thank you.

**Comment by bluca** [comment]
This is not related to bumblebee, but anyway:

installing linux-image-amd64 from jessie-backports is the right thing, but that's only the kernel image, for the nvidia proprietary driver you also need the kernel headers so that the out-of-tree kernel modules can be built for the new kernel

```sudo apt-get install -t jessie-backports linux-image-amd64 linux-headers-amd64```

**Comment by EgamoPi** [comment]
Thank you for your fast reply, and sorry If there is not a link with bumblebee, I was scared to mess up my once more my laptop (since the last time we talked, 6 days ago, I did 5 new installation.. cool right ?)
Well IT WORRRKSS (Déjà vu hein ?^^) I have some more questions : Ok so if I well understood the backports repository, uses the stretch package without affecting the stable kernel ? So what I did first is installing the new kernel from the backport but without the headers.. What are the headers ? And that means that every time that I update my kernel I have to do the same thing with the headers ?
Any way thanks for your precious help, because without you I would have probably jump from my window (russian humour..) 
Thanks a lot.

**Comment by bluca** [comment]
linux-headers-amd64 and linux-image-amd64 are metapackages, which means they are empty and depend on the actual latest version. Since you installed those from backports, from now on when a new kernel is added to the backports you will automatically upgrade to it.

The headers are needed to build out-of-tree kernel modules, like the nvidia driver's. While the kernel userspace API/ABI is stable, and that's why you can simply upgrade your kernel without recompiling all applications, the in-kernel ABI is intentionally not, so to build a kernel module for a kernel version you need the exact headers for that version.

All of this can be found on the Debian wiki, somewhere, and on various stack overflow questions.

Since the problem is solved I'll close the issue now.
