### ISSUE TITLE
Fedora 27 with kernel 4.14.3

### ISSUE THREAD

**Issue by kmare** [Bumblebee-Project/Bumblebee#929]
It looks like bumblebee can't install the nvidia driver on fedora after updating to kernel 4.14.3 (which just got in fedora stable).
@gsgatlin do you think you could update the repo with a newer driver compatible with 4.14 (if it even exists now)?
 
Attached is log file.

[nvidia-installer.log](https://github.com/Bumblebee-Project/Bumblebee/files/1546156/nvidia-installer.log)

**Comment by gsgatlin** [comment]
I see there is a 384.98 so I will work on updating to that version and test it out with 4.14 series kernel. I just updated to fedora 27 myself recently.

**Comment by kmare** [comment]
@gsgatlin  thank you so much, it's much appreciated!

**Comment by kmare** [comment]
@gsgatlin I just updated the kernel and nvidia driver (387.34 from the negativo repo) on my desktop pc (no bumblebee of course) and it booted fine. So I guess it's indeed an nvidia driver version problem.

**Comment by gsgatlin** [comment]
Ok. You should be able to dnf update on fedora 27 to bumblebee-nvidia-384.98-1

The commits that changed are

https://github.com/gsgatlin/bumblebee-nvidia/commit/b002e08fdb07c025b7449929378df6bbb858133f

and

https://github.com/gsgatlin/optimus-rpms/commit/4403b294df8359d7bc281e72745b35d0f779892f

I have verified this works on 4.14 series kernel on fedora 27 with thinkpad and ideapad from lenovo.

You may need to clean the cache IIRC. For fedora 28 its being moved to another yum repo latter this week so that doesn't exists yet for rawhide.

**Comment by gsgatlin** [comment]
Hey I forgot to sign the package but that is fixed now if anyone ran into problems earlier today.

**Comment by kmare** [comment]
@gsgatlin thank you so much! worked like a charm after you signed the package!
ASUS ZenBook Pro UX501VW
